name: Update pkg.go.dev

# Run when pushed to main and when creating vX.Y.Z tags
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-pkg:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Preparation
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Request pkg.go.dev for rescan
      - name: Request pkg.go.dev update
        run: |
          URL="https://pkg.go.dev/github.com/SeRj-ThuramS/go-container?tab=doc"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          echo "HTTP Status Code: $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "⚠️ Error updating pkg.go.dev"
            exit 1
          else
            echo "✅ pkg.go.dev successfully updated"
          fi
