name: Update pkg.go.dev

on:
  release:
    types: [published] # Trigger on a new GitHub release
  push:
    branches:
      - main # Or the branch where your main development happens

jobs:
  update-pkg-go-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18.10' # Specify your desired Go version

      - name: Get module path
        id: get-module-path
        run: echo "MODULE_PATH=$(go list -m)" >> $GITHUB_OUTPUT

      - name: Trigger pkg.go.dev update
        run: go get ${{ steps.get-module-path.outputs.MODULE_PATH }}@latest